name: reusable workflow
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the deployable artifact files
        required: false
        default: dist-files
        type: string
    outputs:
      result:
        description: The result of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}
      # secrets:
      #   some-secret:
      #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-results.outputs.DEPLOYMENT_STATUS }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Set result outputs
        id: set-results
        run: |
          echo "DEPLOYMENT_STATUS=success" >> $GITHUB_OUTPUT
          echo "Set deployment status output to 'success'"